# -*- coding: utf-8 -*-
"""Untitled1.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1NeLDGj4Ay5LNYbk8VFXGniSRwrjxEFJn
"""

names =["Kagetera", "John" , "Peter" , "Alex", "Claude,"]
names.sort
names.append("mutegetsi")
names.append("university of kigali")
names.append("gerves")
print (names)